namespace Threadlink.Shared
{
    /// <summary>
    /// AUTO-GENERATED BY THREADLINK'S CODEGEN. DO NOT EDIT MANUALLY.
    /// <para></para>
    /// ID Markers of the scenes referenced by the <see cref="UnityEngine.AddressableAssets"/> pipeline.
    /// </summary>
    public enum SceneIDs : uint
    {
        
    }
}