namespace Threadlink.Editor
{
    using System.IO;
    using System.Text;
    using Threadlink.Shared;
    using Threadlink.Utilities.Strings;
    using UnityEditor;

    internal sealed class ThreadlinkIDsImporter : AssetPostprocessor
    {
        internal static readonly StringBuilder StringBuilder = new();

        internal static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
        {
            if (!ThreadlinkConfigFinder.TryGetConfig(out ThreadlinkEditorConfig config)
            || config.UserDomainDefinitionsFolder == null
            || config.UserDomainScriptsFolder == null)
                return;

            var definitionsPath = AssetDatabase.GetAssetPath(config.UserDomainDefinitionsFolder);

            if (NeedsRebuild(definitionsPath, imported) || NeedsRebuild(definitionsPath, deleted))
                GenerateEnums(definitionsPath, AssetDatabase.GetAssetPath(config.UserDomainScriptsFolder));
        }

        private static bool NeedsRebuild(string directory, string[] assetPaths)
        {
            foreach (string path in assetPaths)
            {
                if (path.StartsWith(directory) && path.EndsWith(".txt"))
                    return true;
            }

            return false;
        }

        private static void GenerateEnums(string definitionsDirectory, string codeDirectory)
        {
            var txtFiles = Directory.GetFiles(definitionsDirectory.ToAbsolutePath(), "*.txt");

            foreach (string file in txtFiles)
            {
                string domainName = Path.GetFileNameWithoutExtension(file);
                string outputPath = $"{codeDirectory.ToAbsolutePath()}/{domainName}.cs";

                StringBuilder.Clear();
                StringBuilder.AppendLine($"namespace {nameof(Threadlink.User)}");
                StringBuilder.AppendLine("{");
                StringBuilder.AppendLine("// AUTO-GENERATED BY THREADLINK'S CODEGEN. DO NOT MODIFY MANUALLY.");
                StringBuilder.AppendLine($"public enum {domainName} : int");
                StringBuilder.AppendLine("{");
                StringBuilder.AppendLine("None = 0,");

                var lines = File.ReadAllLines(file);
                foreach (string line in lines)
                {
                    string cleanName = line.Trim();

                    if (string.IsNullOrEmpty(cleanName) || cleanName.StartsWith("//"))
                        continue;

                    string safeCsharpName = cleanName.Replace(" ", string.Empty).Replace("-", "_");
                    int hash = HashFunctions.ToXxHash32(safeCsharpName);

                    StringBuilder.AppendLine($"{safeCsharpName} = {hash},");
                }

                StringBuilder.AppendLine("}");
                StringBuilder.AppendLine("}");
                File.WriteAllText(outputPath, CSharpier.CodeFormatter.Format(StringBuilder.ToString()).Code);
            }

            StringBuilder.Clear();
            AssetDatabase.Refresh();
        }
    }
}
