namespace Threadlink.Vault
{
    public partial class Vault
    {
        /// <summary>
        /// AUTO-GENERATED BY THREADLINK'S CODEGEN. DO NOT EDIT MANUALLY.
        /// <para></para>
        /// ID Markers of the data fields populating <see cref="Vault"/> assets.
        /// </summary>
        public enum DataFields : ushort
        {
            None,
            
        }
    }
}