namespace Threadlink.Deterministic
{
    public static partial class StatelessRNG
    {
        /// <summary>
        /// AUTO-GENERATED BY THREADLINK'S CODEGEN. DO NOT EDIT MANUALLY.
        /// <para></para>
        /// ID Markers of the RNG Domains used in <see cref="StatelessRNG"/>.
        /// This is an inentionally byte-backed enum, to encourage a more organic
        /// and human way of thinking about semantic encapsulation.
        /// <para></para>
        /// ATTENTION: Do NOT change the order of your domain entries in any way after generating them!
        /// This is crucial to maintaining determinism across versions, or even during production.
        /// If you no longer want to use a generated domain, remove all references to it and rename it
        /// (to something like "Unused_Domain_X") in the user template file, then re-generate this enum.
        /// </summary>
        public enum Domains : byte { }
    }
}
