namespace Threadlink.Shared
{
    public static partial class ThreadlinkIDs
    {
        public static partial class Addressables
        {
            /// <summary>
            /// AUTO-GENERATED BY THREADLINK'S CODEGEN. DO NOT EDIT MANUALLY.
            /// <para></para>
            /// ID Markers of the assets referenced by the <see cref="UnityEngine.AddressableAssets"/> pipeline.
            /// </summary>
            public enum Assets : int
            {
                #region Native Assets:
                None = -1,
                #endregion

                #region User Assets:
                
                #endregion
            }
        }
    }
}